INSERT IGNORE INTO games (slug,name,developer,engine,confirmed,dimension,platform,scale,year) VALUES
 ('cs2','Counter-Strike 2','Valve','Source 2',1,'3D','steam','aaa',2023),
 ('dota2','Dota 2','Valve','Source 2',1,'3D','steam','aaa',2013),
 ('palworld','Palworld','Pocketpair','Unreal Engine 5',1,'3D','steam','team',2024),
 ('pubg','PUBG: BATTLEGROUNDS','Krafton','Unreal Engine 4',1,'3D','steam','aaa',2017),
 ('diablo4','Diablo IV','Blizzard','In-house',1,'3D','steam','aaa',2023),
 ('valorant','VALORANT','Riot Games','Unreal Engine 4',1,'3D','steam','aaa',2020),
 ('eldenring','Elden Ring','FromSoftware','In-house',1,'3D','steam','aaa',2022),
 ('tlou','The Last of Us Part I','Naughty Dog','In-house',1,'3D','console','aaa',2022),
 ('cyberpunk','Cyberpunk 2077','CD Projekt Red','REDengine 4',1,'3D','steam','aaa',2020),
 ('balatro','Balatro','LocalThunk','LOVE 2D (Lua)',1,'2D','steam','solo',2024),
 ('deadcells','Dead Cells','Motion Twin','Heaps (Haxe)',1,'2D','steam','team',2018),
 ('hollowknight','Hollow Knight','Team Cherry','Unity',1,'2D','steam','team',2017),
 ('celeste','Celeste','Maddy Makes Games','MonoGame',1,'2D','steam','team',2018),
 ('undertale','Undertale','Toby Fox','GameMaker',1,'2D','steam','solo',2015),
 ('stardew','Stardew Valley','ConcernedApe','MonoGame',1,'2D','steam','solo',2016),
 ('lethalcompany','Lethal Company','Zeekerss','Unity',1,'3D','steam','solo',2023),
 ('vampiresurvivors','Vampire Survivors','poncle','Unity',0,'2D','steam','solo',2022),
 ('slaythespire','Slay the Spire','Mega Crit','libGDX',1,'2D','steam','team',2019),
 ('cuphead','Cuphead','Studio MDHR','Unity',1,'2D','steam','team',2017),
 ('valheim','Valheim','Iron Gate','Unity',1,'3D','steam','team',2021),
 ('terraria','Terraria','Re-Logic','XNA',1,'2D','steam','team',2011),
 ('hades','Hades','Supergiant','In-house',1,'2D','steam','team',2020),
 ('genshin','Genshin Impact','miHoYo','Unity',1,'3D','mobile','aaa',2020),
 ('amongus','Among Us','Innersloth','Unity',1,'2D','mobile','team',2018),
 ('monumentvalley','Monument Valley','ustwo games','Unity',1,'3D','mobile','team',2014);
