-- 게임별 엔진 시드 212종.
--
-- 프론트가 들고 있던 정적 배열을 그대로 옮겼다. 출처는 PCGamingWiki 의
-- 엔진 공개 자료와 SteamSpy 집계이며, confirmed=false 는 업계 추정이다.
-- stack 은 게임마다 항목 수가 달라 컬럼으로 못 펴고 JSONB 로 둔다.
--
-- 이 파일은 손으로 쓰지 않았다. app/src/data/games.ts 에서 생성했다.

-- 0002 가 심은 25종과 슬러그 규칙이 달라 그대로 두면 같은 게임이 두 번 들어간다.
-- 이 파일이 권위 있는 시드이므로 앞에서 비운다. games 를 참조하는 테이블은 없다.
TRUNCATE games RESTART IDENTITY;

INSERT INTO games
  (slug, name, developer, engine, confirmed, category, scale, year, rank, owners, positive, stack)
VALUES
 ('counter-strike-2','Counter-Strike 2','Valve','Source 2',TRUE,'steam','aaa',2023,1,NULL,NULL,'[{"name":"Source 2","role":"엔진","confirmed":true},{"name":"자체 툴체인","role":"제작","confirmed":true},{"name":"Steam Workshop","role":"커뮤니티 에셋","confirmed":true}]'::jsonb),
 ('dota-2','Dota 2','Valve','Source 2',TRUE,'steam','aaa',2013,2,NULL,NULL,'[{"name":"Source 2","role":"엔진","confirmed":true},{"name":"Steam Workshop","role":"커뮤니티 에셋","confirmed":true},{"name":"Panorama UI","role":"UI","confirmed":false}]'::jsonb),
 ('palworld','Palworld','Pocketpair','Unreal Engine 5',TRUE,'steam','team',2024,4,NULL,NULL,'[{"name":"Unreal Engine 5","role":"엔진","confirmed":true},{"name":"Blueprint","role":"로직","confirmed":false},{"name":"전용 서버","role":"네트워크","confirmed":false}]'::jsonb),
 ('apex-legends','Apex Legends','Respawn','Source (개조)',TRUE,'steam','aaa',2019,5,NULL,NULL,'[{"name":"Source (개조)","role":"엔진","confirmed":true},{"name":"자체 애니메이션","role":"제작","confirmed":false}]'::jsonb),
 ('marvel-rivals','Marvel Rivals','NetEase','Unreal Engine 5',TRUE,'steam','aaa',2024,8,NULL,NULL,'[{"name":"Unreal Engine 5","role":"엔진","confirmed":true},{"name":"Lumen , Nanite","role":"렌더","confirmed":false},{"name":"Wwise","role":"오디오","confirmed":false}]'::jsonb),
 ('pubg-battlegrounds','PUBG: BATTLEGROUNDS','Krafton','Unreal Engine 4',TRUE,'steam','aaa',2017,10,NULL,NULL,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true},{"name":"관심영역 동기화","role":"네트워크","confirmed":false},{"name":"FMOD","role":"오디오","confirmed":false}]'::jsonb),
 ('assassin-s-creed-black-flag-resynced','Assassin''s Creed Black Flag Resynced','Ubisoft','AnvilNext (자체)',FALSE,'steam','aaa',2026,6,NULL,NULL,'[{"name":"AnvilNext 계열","role":"엔진","confirmed":false},{"name":"자체 파이프라인","role":"제작","confirmed":false}]'::jsonb),
 ('halo-campaign-evolved','Halo: Campaign Evolved','Halo Studios','Unreal Engine 5',FALSE,'steam','aaa',2026,3,NULL,NULL,'[{"name":"Unreal Engine 5","role":"엔진","confirmed":false},{"name":"자체 에셋 이관","role":"제작","confirmed":false}]'::jsonb),
 ('diablo-iv','Diablo IV','Blizzard','자체 엔진',TRUE,'steam','aaa',2023,NULL,NULL,NULL,'[{"name":"자체 엔진","role":"엔진","confirmed":true},{"name":"사내 아트팀","role":"제작","confirmed":true}]'::jsonb),
 ('valorant','VALORANT','Riot Games','Unreal Engine 4',TRUE,'steam','aaa',2020,NULL,NULL,NULL,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true},{"name":"자체 안티치트","role":"보안","confirmed":false},{"name":"사내 아트팀","role":"제작","confirmed":true}]'::jsonb),
 ('balatro','Balatro','LocalThunk','LÖVE 2D (Lua)',TRUE,'steam','solo',2024,NULL,NULL,NULL,'[{"name":"LÖVE 2D","role":"엔진","confirmed":true},{"name":"Lua","role":"언어","confirmed":true},{"name":"자체 셰이더","role":"연출","confirmed":false}]'::jsonb),
 ('dead-cells','Dead Cells','Motion Twin','Heaps (Haxe)',TRUE,'steam','team',2018,NULL,NULL,NULL,'[{"name":"Heaps.io","role":"엔진","confirmed":true},{"name":"Haxe","role":"언어","confirmed":true},{"name":"LDtk","role":"레벨","confirmed":true},{"name":"FMOD","role":"오디오","confirmed":false}]'::jsonb),
 ('hollow-knight','Hollow Knight','Team Cherry','Unity',TRUE,'steam','team',2017,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"PlayMaker","role":"로직","confirmed":true},{"name":"Wwise","role":"오디오","confirmed":false}]'::jsonb),
 ('celeste','Celeste','Maddy Makes Games','MonoGame (XNA)',TRUE,'steam','team',2018,NULL,NULL,NULL,'[{"name":"MonoGame","role":"엔진","confirmed":true},{"name":"C#","role":"언어","confirmed":true},{"name":"Ogmo Editor","role":"레벨","confirmed":false}]'::jsonb),
 ('undertale','Undertale','Toby Fox','GameMaker',TRUE,'steam','solo',2015,NULL,NULL,NULL,'[{"name":"GameMaker","role":"엔진","confirmed":true},{"name":"GML","role":"언어","confirmed":true},{"name":"FL Studio","role":"음악","confirmed":false}]'::jsonb),
 ('stardew-valley','Stardew Valley','ConcernedApe','MonoGame (XNA)',TRUE,'steam','solo',2016,NULL,NULL,NULL,'[{"name":"MonoGame","role":"엔진","confirmed":true},{"name":"C#","role":"언어","confirmed":true},{"name":"자체 타일 시스템","role":"레벨","confirmed":false}]'::jsonb),
 ('lethal-company','Lethal Company','Zeekerss','Unity',TRUE,'steam','solo',2023,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"에셋스토어 조합","role":"아트","confirmed":true},{"name":"근접 음성채팅","role":"시스템","confirmed":false}]'::jsonb),
 ('vampire-survivors','Vampire Survivors','poncle','Unity',FALSE,'steam','solo',2022,NULL,NULL,NULL,'[{"name":"Unity","role":"현재 엔진","confirmed":false},{"name":"C#","role":"언어","confirmed":false},{"name":"모바일 , 콘솔 동시 대응","role":"배포","confirmed":true}]'::jsonb),
 ('slay-the-spire','Slay the Spire','Mega Crit','libGDX (Java)',TRUE,'steam','team',2019,NULL,NULL,NULL,'[{"name":"libGDX","role":"엔진","confirmed":true},{"name":"Java","role":"언어","confirmed":true},{"name":"모드 API","role":"확장","confirmed":false}]'::jsonb),
 ('cuphead','Cuphead','Studio MDHR','Unity',TRUE,'steam','team',2017,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"수작업 셀 애니","role":"아트","confirmed":true}]'::jsonb),
 ('valheim','Valheim','Iron Gate','Unity',TRUE,'steam','team',2021,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"절차적 지형","role":"레벨","confirmed":false}]'::jsonb),
 ('terraria','Terraria','Re-Logic','XNA',TRUE,'steam','team',2011,NULL,NULL,NULL,'[{"name":"XNA","role":"엔진","confirmed":true},{"name":"C#","role":"언어","confirmed":true}]'::jsonb),
 ('hades','Hades','Supergiant','자체 엔진',TRUE,'steam','team',2020,NULL,NULL,NULL,'[{"name":"자체 엔진","role":"엔진","confirmed":true},{"name":"수작업 일러스트","role":"아트","confirmed":true},{"name":"FMOD","role":"오디오","confirmed":false}]'::jsonb),
 ('risk-of-rain-2','Risk of Rain 2','Hopoo Games','Unity',TRUE,'steam','team',2020,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"로우폴리 아트","role":"아트","confirmed":false}]'::jsonb),
 ('cult-of-the-lamb','Cult of the Lamb','Massive Monster','Unity',TRUE,'steam','team',2022,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"Spine","role":"2D 애니","confirmed":false}]'::jsonb),
 ('katana-zero','Katana ZERO','Askiisoft','GameMaker',TRUE,'steam','team',2019,NULL,NULL,NULL,'[{"name":"GameMaker","role":"엔진","confirmed":true},{"name":"Aseprite","role":"도트","confirmed":false}]'::jsonb),
 ('hyper-light-drifter','Hyper Light Drifter','Heart Machine','GameMaker',TRUE,'steam','team',2016,NULL,NULL,NULL,'[{"name":"GameMaker","role":"엔진","confirmed":true},{"name":"Aseprite","role":"도트","confirmed":false}]'::jsonb),
 ('blasphemous','Blasphemous','The Game Kitchen','Unity',TRUE,'steam','team',2019,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"수작업 도트","role":"아트","confirmed":true}]'::jsonb),
 ('tunic','Tunic','Andrew Shouldice','Unity',TRUE,'steam','solo',2022,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"로우폴리","role":"아트","confirmed":false}]'::jsonb),
 ('papers-please','Papers, Please','Lucas Pope','Haxe / OpenFL',TRUE,'steam','solo',2013,NULL,NULL,NULL,'[{"name":"Haxe / OpenFL","role":"엔진","confirmed":true},{"name":"자체 UI","role":"제작","confirmed":false}]'::jsonb),
 ('','원신','miHoYo','Unity',TRUE,'mobile','aaa',2020,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"자체 셰이더","role":"렌더","confirmed":false},{"name":"Wwise","role":"오디오","confirmed":false}]'::jsonb),
 ('among-us','Among Us','Innersloth','Unity',TRUE,'mobile','team',2018,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"단순 2D 아트","role":"아트","confirmed":false}]'::jsonb),
 ('monument-valley','Monument Valley','ustwo games','Unity',TRUE,'mobile','team',2014,NULL,NULL,NULL,'[{"name":"Unity","role":"엔진","confirmed":true},{"name":"자체 착시 시스템","role":"제작","confirmed":false}]'::jsonb),
 ('counter-strike-global-offensive','Counter-Strike: Global Offensive','Valve','Source',TRUE,'steam','aaa',2012,NULL,'1억+',7642084,'[{"name":"Source","role":"엔진","confirmed":true}]'::jsonb),
 ('black-myth-wukong','Black Myth: Wukong','Game Science','Unreal Engine 5',TRUE,'steam','aaa',2024,NULL,'5000만+',1111720,'[{"name":"Unreal Engine 5","role":"엔진","confirmed":true}]'::jsonb),
 ('baldur-s-gate-3','Baldur''s Gate 3','Larian Studios','Divinity Engine',TRUE,'steam','aaa',2023,NULL,'2000만+',736688,'[{"name":"Divinity Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('cyberpunk-2077','Cyberpunk 2077','CD PROJEKT RED','REDengine',TRUE,'steam','aaa',2020,NULL,'2000만+',713071,'[{"name":"REDengine","role":"엔진","confirmed":true}]'::jsonb),
 ('apex-legends-2','Apex Legends','Respawn','Source',TRUE,'steam','aaa',2019,NULL,'1억+',668053,'[{"name":"Source","role":"엔진","confirmed":true}]'::jsonb),
 ('among-us-2','Among Us','Innersloth','Unity',TRUE,'steam','aaa',2018,NULL,'2000만+',643681,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('dead-by-daylight','Dead by Daylight','Behaviour Interactive Inc.','Unreal Engine 4',TRUE,'steam','aaa',2016,NULL,'2000만+',630223,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('ark-survival-evolved','ARK: Survival Evolved','Studio Wildcard','Unreal Engine 4',TRUE,'steam','aaa',2017,NULL,'2000만+',612177,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-modern-warfare-ii','Call of Duty: Modern Warfare II','Treyarch','IW engine',TRUE,'steam','aaa',2022,NULL,'5000만+',419594,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('bloons-td-6','Bloons TD 6','Ninja Kiwi','Unity',TRUE,'steam','team',2018,NULL,'200만+',344269,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('dayz','DayZ','Bohemia Interactive','Enfusion',TRUE,'steam','aaa',2018,NULL,'1000만+',330349,'[{"name":"Enfusion","role":"엔진","confirmed":true}]'::jsonb),
 ('7-days-to-die','7 Days to Die','The Fun Pimps','Unity',TRUE,'steam','aaa',2024,NULL,'1000만+',327889,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('brawlhalla','Brawlhalla','Blue Mammoth Games','Adobe AIR',TRUE,'steam','aaa',2017,NULL,'2000만+',314809,'[{"name":"Adobe AIR","role":"엔진","confirmed":true}]'::jsonb),
 ('borderlands-2','Borderlands 2','Gearbox Software','Unreal Engine 3',TRUE,'steam','aaa',2012,NULL,'1000만+',272900,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('cities-skylines','Cities: Skylines','Colossal Order','Unity',TRUE,'steam','aaa',2015,NULL,'1000만+',256362,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('arma-3','Arma 3','Bohemia Interactive','Real Virtuality',TRUE,'steam','aaa',2013,NULL,'1000만+',256128,'[{"name":"Real Virtuality","role":"엔진","confirmed":true}]'::jsonb),
 ('counter-strike','Counter-Strike','Valve','GoldSrc',TRUE,'steam','aaa',2000,NULL,'1000만+',243818,'[{"name":"GoldSrc","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-black-ops-iii','Call of Duty: Black Ops III','Treyarch','IW engine',TRUE,'steam','aaa',2015,NULL,'500만+',181306,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('cuphead-2','Cuphead','Studio MDHR Entertainment Inc.','Unity',TRUE,'steam','aaa',2017,NULL,'500만+',179894,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('battlefield-v','Battlefield V','DICE','Frostbite 3',TRUE,'steam','aaa',2018,NULL,'1000만+',177352,'[{"name":"Frostbite 3","role":"엔진","confirmed":true}]'::jsonb),
 ('counter-strike-source','Counter-Strike: Source','Valve','Source',TRUE,'steam','aaa',2004,NULL,'1000만+',175426,'[{"name":"Source","role":"엔진","confirmed":true}]'::jsonb),
 ('american-truck-simulator','American Truck Simulator','SCS Software','Prism3D',TRUE,'steam','team',2016,NULL,'200만+',169735,'[{"name":"Prism3D","role":"엔진","confirmed":true}]'::jsonb),
 ('battlefield-1','Battlefield 1','DICE','Frostbite 3',TRUE,'steam','aaa',2016,NULL,'500만+',166775,'[{"name":"Frostbite 3","role":"엔진","confirmed":true}]'::jsonb),
 ('dead-cells-2','Dead Cells','Motion Twin','Heaps',TRUE,'steam','aaa',2018,NULL,'500만+',163549,'[{"name":"Heaps","role":"엔진","confirmed":true}]'::jsonb),
 ('age-of-empires-ii-definitive-edition','Age of Empires II: Definitive Edition','World''s Edge','Genie',TRUE,'steam','team',2019,NULL,'200만+',154061,'[{"name":"Genie","role":"엔진","confirmed":true}]'::jsonb),
 ('assassin-s-creed-odyssey','Assassin''s Creed Odyssey','Ubisoft Quebec','AnvilNext',TRUE,'steam','aaa',2018,NULL,'500만+',153091,'[{"name":"AnvilNext","role":"엔진","confirmed":true}]'::jsonb),
 ('balatro-2','Balatro','LocalThunk','LÖVE',TRUE,'steam','team',2024,NULL,'200만+',150524,'[{"name":"LÖVE","role":"엔진","confirmed":true}]'::jsonb),
 ('crab-game','Crab Game','Dani','Unity',TRUE,'steam','aaa',2021,NULL,'500만+',139538,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('battlefield-2042','Battlefield 2042','DICE','Frostbite',TRUE,'steam','aaa',2021,NULL,'1000만+',139186,'[{"name":"Frostbite","role":"엔진","confirmed":true}]'::jsonb),
 ('content-warning','Content Warning','Zorro','Unity',TRUE,'steam','aaa',2024,NULL,'500만+',137483,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('bioshock-infinite','BioShock Infinite','Irrational Games','Unreal Engine 3',TRUE,'steam','team',2013,NULL,'200만+',131970,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('borderlands-3','Borderlands 3','Gearbox Software','Unreal Engine 4',TRUE,'steam','team',2019,NULL,'200만+',125248,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('batman-arkham-knight','Batman: Arkham Knight','Rocksteady Studios','Unreal Engine 3',TRUE,'steam','team',2015,NULL,'200만+',124147,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('black-mesa','Black Mesa','Crowbar Collective','Source',TRUE,'steam','team',2020,NULL,'200만+',121562,'[{"name":"Source","role":"엔진","confirmed":true}]'::jsonb),
 ('celeste-2','Celeste','Maddy Makes Games Inc.','FNA',TRUE,'steam','team',2018,NULL,'200만+',117545,'[{"name":"FNA","role":"엔진","confirmed":true}]'::jsonb),
 ('crusader-kings-iii','Crusader Kings III','Paradox Development Studio','Clausewitz',TRUE,'steam','team',2020,NULL,'200만+',114259,'[{"name":"Clausewitz","role":"엔진","confirmed":true}]'::jsonb),
 ('clair-obscur-expedition-33','Clair Obscur: Expedition 33','Sandfall Interactive','Unreal Engine 5',TRUE,'steam','team',2025,NULL,'200만+',106216,'[{"name":"Unreal Engine 5","role":"엔진","confirmed":true}]'::jsonb),
 ('cult-of-the-lamb-2','Cult of the Lamb','Massive Monster','Unity',TRUE,'steam','team',2022,NULL,'200만+',98711,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('assassin-s-creed-origins','Assassin''s Creed Origins','Ubisoft Montreal','AnvilNext',TRUE,'steam','team',2017,NULL,'100만+',97301,'[{"name":"AnvilNext","role":"엔진","confirmed":true}]'::jsonb),
 ('days-gone','Days Gone','Bend Studio','Unreal Engine 4',TRUE,'steam','team',2021,NULL,'200만+',95697,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('brotato','Brotato','Blobfish','Godot',TRUE,'steam','team',2023,NULL,'200만+',94525,'[{"name":"Godot","role":"엔진","confirmed":true}]'::jsonb),
 ('buckshot-roulette','Buckshot Roulette','Mike Klubnika','Godot',TRUE,'steam','team',2023,NULL,'200만+',91745,'[{"name":"Godot","role":"엔진","confirmed":true}]'::jsonb),
 ('company-of-heroes-2','Company of Heroes 2','Relic Entertainment','Essence Engine',TRUE,'steam','aaa',2013,NULL,'500만+',86713,'[{"name":"Essence Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('carx-drift-racing-online','CarX Drift Racing Online','CarX Technologies','Unity',TRUE,'steam','team',2017,NULL,'200만+',79504,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('cookie-clicker','Cookie Clicker','Orteil','Electron',TRUE,'steam','team',2021,NULL,'200만+',77218,'[{"name":"Electron","role":"엔진","confirmed":true}]'::jsonb),
 ('a-way-out','A Way Out','Hazelight Studios','Unreal Engine 4',TRUE,'steam','team',2018,NULL,'200만+',72313,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('beat-saber','Beat Saber','Beat Games','Unity',TRUE,'steam','team',2019,NULL,'200만+',71341,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('barotrauma','Barotrauma','FakeFish','MonoGame',TRUE,'steam','team',2023,NULL,'200만+',70694,'[{"name":"MonoGame","role":"엔진","confirmed":true}]'::jsonb),
 ('battleblock-theater','BattleBlock Theater','The Behemoth','Behemoth Engine',TRUE,'steam','team',2014,NULL,'200만+',69617,'[{"name":"Behemoth Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('a-dance-of-fire-and-ice','A Dance of Fire and Ice','7th Beat Games','Unity',TRUE,'steam','team',2019,NULL,'200만+',69052,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('crusader-kings-ii','Crusader Kings II','Paradox Development Studio','Clausewitz',TRUE,'steam','team',2012,NULL,'200만+',66359,'[{"name":"Clausewitz","role":"엔진","confirmed":true}]'::jsonb),
 ('cry-of-fear','Cry of Fear','Team Psykskallar','GoldSrc',TRUE,'steam','aaa',2013,NULL,'500만+',65852,'[{"name":"GoldSrc","role":"엔진","confirmed":true}]'::jsonb),
 ('albion-online','Albion Online','Sandbox Interactive GmbH','Unity',TRUE,'steam','team',2017,NULL,'200만+',65583,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('black-desert','Black Desert','Pearl Abyss','Black Desert Engine',TRUE,'steam','aaa',2014,NULL,'500만+',64416,'[{"name":"Black Desert Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('black-squad','Black Squad','VALOFE','Unreal Engine 3',TRUE,'steam','aaa',2019,NULL,'1000만+',62042,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('battlefield-4','Battlefield 4','DICE','Frostbite 3',TRUE,'steam','team',2013,NULL,'100만+',60650,'[{"name":"Frostbite 3","role":"엔진","confirmed":true}]'::jsonb),
 ('a-plague-tale-innocence','A Plague Tale: Innocence','Asobo Studio','Zouna',TRUE,'steam','team',2019,NULL,'100만+',58909,'[{"name":"Zouna","role":"엔진","confirmed":true}]'::jsonb),
 ('assassin-s-creed-unity','Assassin''s Creed Unity','Ubisoft','AnvilNext',TRUE,'steam','team',2014,NULL,'200만+',58065,'[{"name":"AnvilNext","role":"엔진","confirmed":true}]'::jsonb),
 ('broforce','Broforce','Free Lives','Unity',TRUE,'steam','team',2015,NULL,'200만+',57080,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('alien-isolation','Alien: Isolation','Creative Assembly','Cathode',TRUE,'steam','team',2014,NULL,'200만+',56716,'[{"name":"Cathode","role":"엔진","confirmed":true}]'::jsonb),
 ('clicker-heroes','Clicker Heroes','Playsaurus','Adobe AIR',TRUE,'steam','aaa',2015,NULL,'500만+',54989,'[{"name":"Adobe AIR","role":"엔진","confirmed":true}]'::jsonb),
 ('chivalry-medieval-warfare','Chivalry: Medieval Warfare','Torn Banner Studios','Unreal Engine 3',TRUE,'steam','aaa',2012,NULL,'500만+',54016,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('adventure-capitalist','AdVenture Capitalist','Hyper Hippo Games','Unity',TRUE,'steam','aaa',2015,NULL,'500만+',51968,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('batman-arkham-origins','Batman: Arkham Origins','WB Games Montreal','Unreal Engine 3',TRUE,'steam','team',2013,NULL,'200만+',51192,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('core-keeper','Core Keeper','Pugstorm','Unity',TRUE,'steam','team',2024,NULL,'100만+',51042,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('a-hat-in-time','A Hat in Time','Gears for Breakfast','Unreal Engine 3',TRUE,'steam','team',2017,NULL,'50만+',50577,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('battlerite','Battlerite','Stunlock Studios','Unity',TRUE,'steam','team',2017,NULL,'200만+',50196,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('chained-together','Chained Together','Anegar Games','Unreal Engine 5',TRUE,'steam','team',2024,NULL,'200만+',48180,'[{"name":"Unreal Engine 5","role":"엔진","confirmed":true}]'::jsonb),
 ('bioshock-remastered','BioShock Remastered','2K Boston','Unreal Engine 2.5',TRUE,'steam','team',2016,NULL,'200만+',47962,'[{"name":"Unreal Engine 2.5","role":"엔진","confirmed":true}]'::jsonb),
 ('besiege','Besiege','Spiderling Studios','Unity',TRUE,'steam','team',2020,NULL,'100만+',47491,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('brick-rigs','Brick Rigs','Fluppisoft GmbH','Unreal Engine 4',TRUE,'steam','team',2023,NULL,'100만+',47391,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('car-mechanic-simulator-2018','Car Mechanic Simulator 2018','Red Dot Games','Unity',TRUE,'steam','team',2017,NULL,'200만+',47065,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('back-4-blood','Back 4 Blood','Turtle Rock Studios','Unreal Engine 4',TRUE,'steam','team',2021,NULL,'100만+',46833,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-world-at-war','Call of Duty: World at War','Treyarch','IW engine',TRUE,'steam','team',2008,NULL,'200만+',46665,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('blasphemous-2','Blasphemous','The Game Kitchen','Unity',TRUE,'steam','team',2019,NULL,'100만+',46393,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('alan-wake','Alan Wake','Remedy Entertainment','Northlight',TRUE,'steam','team',2012,NULL,'200만+',44449,'[{"name":"Northlight","role":"엔진","confirmed":true}]'::jsonb),
 ('age-of-history-ii','Age of History II','Łukasz Jakowski','Java',TRUE,'steam','team',2018,NULL,'100만+',41684,'[{"name":"Java","role":"엔진","confirmed":true}]'::jsonb),
 ('age-of-empires-iii-definitive-edition','Age of Empires III: Definitive Edition','World''s Edge','BANG!',TRUE,'steam','team',2020,NULL,'100만+',40941,'[{"name":"BANG!","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-black-ops-ii','Call of Duty: Black Ops II','Treyarch','IW engine',TRUE,'steam','team',2012,NULL,'200만+',40563,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('cities-skylines-ii','Cities: Skylines II','Iceflake Studios','Unity',TRUE,'steam','team',2023,NULL,'200만+',38697,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-juarez-gunslinger','Call of Juarez: Gunslinger','Techland','Chrome Engine',TRUE,'steam','team',2013,NULL,'200만+',38679,'[{"name":"Chrome Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('chivalry-2','Chivalry 2','Torn Banner Studios','Unreal Engine 4',TRUE,'steam','team',2021,NULL,'200만+',37673,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('bloodstained-ritual-of-the-night','Bloodstained: Ritual of the Night','ArtPlay','Unreal Engine 4',TRUE,'steam','team',2019,NULL,'100만+',36999,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('assetto-corsa-competizione','Assetto Corsa Competizione','Kunos Simulazioni','Unreal Engine 4',TRUE,'steam','team',2019,NULL,'100만+',36035,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('bastion','Bastion','Supergiant Games','FNA',TRUE,'steam','team',2011,NULL,'200만+',35661,'[{"name":"FNA","role":"엔진","confirmed":true}]'::jsonb),
 ('bright-memory-infinite','Bright Memory: Infinite','FYQD-Studio','Unreal Engine 4',TRUE,'steam','team',2021,NULL,'100만+',35622,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('borderlands-the-pre-sequel','Borderlands: The Pre-Sequel','2K Australia','Unreal Engine 3',TRUE,'steam','team',2014,NULL,'200만+',33577,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('age-of-mythology-extended-edition','Age of Mythology: Extended Edition','SkyBox Labs','BANG!',TRUE,'steam','team',2014,NULL,'200만+',32895,'[{"name":"BANG!","role":"엔진","confirmed":true}]'::jsonb),
 ('blood-and-bacon','Blood and Bacon','Big Corporation','XNA',TRUE,'steam','team',2016,NULL,'100만+',32796,'[{"name":"XNA","role":"엔진","confirmed":true}]'::jsonb),
 ('amnesia-the-dark-descent','Amnesia: The Dark Descent','Frictional Games','HPL Engine',TRUE,'steam','team',2010,NULL,'200만+',32258,'[{"name":"HPL Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('clone-drone-in-the-danger-zone','Clone Drone in the Danger Zone','Doborog Games','Unity',TRUE,'steam','team',2021,NULL,'100만+',32025,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('battlefield-bad-company-2','Battlefield: Bad Company 2','DICE','Frostbite 1.5',TRUE,'steam','team',2010,NULL,'200만+',31749,'[{"name":"Frostbite 1.5","role":"엔진","confirmed":true}]'::jsonb),
 ('atomic-heart','Atomic Heart','Mundfish','Unreal Engine 4',TRUE,'steam','team',2023,NULL,'100만+',31167,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('bully-scholarship-edition','Bully: Scholarship Edition','Rockstar New England','Gamebryo',TRUE,'steam','team',2008,NULL,'200만+',30730,'[{"name":"Gamebryo","role":"엔진","confirmed":true}]'::jsonb),
 ('abiotic-factor','Abiotic Factor','Deep Field Games','Unreal Engine 5',TRUE,'steam','team',2025,NULL,'50만+',30157,'[{"name":"Unreal Engine 5","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-wwii','Call of Duty: WWII','Sledgehammer Games','IW engine',TRUE,'steam','team',2017,NULL,'200만+',30055,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('against-the-storm','Against the Storm','Eremite Games','Unity',TRUE,'steam','team',2023,NULL,'50만+',29837,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('bright-memory','Bright Memory','FYQD-Studio','Unreal Engine 4',TRUE,'steam','team',2020,NULL,'100만+',29613,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('danganronpa-trigger-happy-havoc','Danganronpa: Trigger Happy Havoc','Spike Chunsoft Co.','SilverWare',TRUE,'steam','team',2016,NULL,'100만+',29230,'[{"name":"SilverWare","role":"엔진","confirmed":true}]'::jsonb),
 ('bioshock','BioShock','2K Boston','Unreal Engine 2.5',TRUE,'steam','team',2007,NULL,'200만+',29127,'[{"name":"Unreal Engine 2.5","role":"엔진","confirmed":true}]'::jsonb),
 ('car-mechanic-simulator-2021','Car Mechanic Simulator 2021','Red Dot Games','Unity',TRUE,'steam','team',2021,NULL,'100만+',28630,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('bayonetta','Bayonetta','PlatinumGames','Platinum Engine',TRUE,'steam','team',2017,NULL,'100만+',26797,'[{"name":"Platinum Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('crab-champions','Crab Champions','Noisestorm','Unreal Engine 4',TRUE,'steam','team',2023,NULL,'50만+',26307,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('bendy-and-the-ink-machine','Bendy and the Ink Machine','Joey Drew Studios','Unity',TRUE,'steam','team',2017,NULL,'50만+',26052,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('danganronpa-2-goodbye-despair','Danganronpa 2: Goodbye Despair','Spike Chunsoft Co.','SilverWare',TRUE,'steam','team',2016,NULL,'50만+',25613,'[{"name":"SilverWare","role":"엔진","confirmed":true}]'::jsonb),
 ('beholder','Beholder','Alawar Stargaze (Warm Lamp Games)','Unity',TRUE,'steam','team',2016,NULL,'100만+',25444,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('city-car-driving','City Car Driving','Forward Development','Nebula Device',TRUE,'steam','team',2010,NULL,'50만+',24830,'[{"name":"Nebula Device","role":"엔진","confirmed":true}]'::jsonb),
 ('crush-crush','Crush Crush','Sad Panda Studios','Unity',TRUE,'steam','team',2016,NULL,'100만+',24246,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('crypt-of-the-necrodancer','Crypt of the NecroDancer','Brace Yourself Games','Monkey X',TRUE,'steam','team',2015,NULL,'100만+',24053,'[{"name":"Monkey X","role":"엔진","confirmed":true}]'::jsonb),
 ('creativerse','Creativerse','Playful Corp.','Unity',TRUE,'steam','team',2017,NULL,'100만+',24051,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('assassin-s-creed-syndicate','Assassin''s Creed Syndicate','Ubisoft Quebec','AnvilNext',TRUE,'steam','team',2015,NULL,'200만+',23779,'[{"name":"AnvilNext","role":"엔진","confirmed":true}]'::jsonb),
 ('apb-reloaded','APB Reloaded','Little Orbit','Unreal Engine 3',TRUE,'steam','aaa',2010,NULL,'500만+',23693,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('chinese-parents','Chinese Parents','墨鱼玩游戏','Unity',TRUE,'steam','team',2018,NULL,'100만+',23459,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('arma-reforger','Arma Reforger','Bohemia Interactive','Enfusion',TRUE,'indie','team',2023,NULL,'20만+',23326,'[{"name":"Enfusion","role":"엔진","confirmed":true}]'::jsonb),
 ('conqueror-s-blade','Conqueror''s Blade','Booming Tech','Chaos',TRUE,'steam','team',2020,NULL,'200만+',22576,'[{"name":"Chaos","role":"엔진","confirmed":true}]'::jsonb),
 ('alice-madness-returns','Alice: Madness Returns','Spicy Horse Games','Unreal Engine 3',TRUE,'steam','team',2011,NULL,'100만+',21729,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('crime-scene-cleaner','Crime Scene Cleaner','President Studio','Unity',TRUE,'steam','team',2024,NULL,'50만+',21567,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('assassin-s-creed-valhalla','Assassin''s Creed Valhalla','Ubisoft Montreal','Ubisoft Anvil',TRUE,'steam','team',2020,NULL,'50만+',21554,'[{"name":"Ubisoft Anvil","role":"엔진","confirmed":true}]'::jsonb),
 ('baba-is-you','Baba Is You','Hempuli Oy','Chowdren',TRUE,'steam','team',2019,NULL,'100만+',21441,'[{"name":"Chowdren","role":"엔진","confirmed":true}]'::jsonb),
 ('cell-to-singularity-evolution-never-ends','Cell to Singularity - Evolution Never Ends','Computer Lunch','Unity',TRUE,'steam','team',2021,NULL,'100만+',21284,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('blackwake','Blackwake','Mastfire Studios Pty Ltd','Unity',TRUE,'steam','team',2020,NULL,'50만+',20925,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('day-of-defeat-source','Day of Defeat: Source','Valve','Source',TRUE,'steam','team',2005,NULL,'200만+',20798,'[{"name":"Source","role":"엔진","confirmed":true}]'::jsonb),
 ('darkwood','Darkwood','Acid Wizard Studio','Unity',TRUE,'steam','team',2017,NULL,'100만+',20529,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('anno-1800','Anno 1800','Ubisoft Mainz','RD3D',TRUE,'steam','team',2019,NULL,'100만+',20368,'[{"name":"RD3D","role":"엔진","confirmed":true}]'::jsonb),
 ('alien-swarm','Alien Swarm','Valve','Source',TRUE,'steam','team',2010,NULL,'200만+',20179,'[{"name":"Source","role":"엔진","confirmed":true}]'::jsonb),
 ('cruelty-squad','Cruelty Squad','Consumer Softproducts','Godot',TRUE,'steam','team',2021,NULL,'100만+',20136,'[{"name":"Godot","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-ghosts','Call of Duty: Ghosts','Infinity Ward','IW engine',TRUE,'steam','team',2013,NULL,'100만+',19917,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('aliens-fireteam-elite','Aliens: Fireteam Elite','Cold Iron Studios','Unreal Engine 4',TRUE,'steam','team',2021,NULL,'100만+',19732,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('amazing-cultivation-simulator','Amazing Cultivation Simulator','GSQ Games','Unity',TRUE,'steam','team',2020,NULL,'50만+',19720,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('contraband-police','Contraband Police','Crazy Rocks','Unity',TRUE,'steam','team',2018,NULL,'50만+',19433,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('coral-island','Coral Island','Stairway Games','Unreal Engine 4',TRUE,'steam','team',2023,NULL,'50만+',19184,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('company-of-heroes-3','Company of Heroes 3','Relic Entertainment','Essence Engine',TRUE,'steam','team',2023,NULL,'100만+',18936,'[{"name":"Essence Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('dark-deception','Dark Deception','Glowstick Entertainment','Unreal Engine 4',TRUE,'steam','team',2018,NULL,'100만+',18879,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('bioshock-2-remastered','BioShock 2 Remastered','2K Marin','Unreal Engine 2.5',TRUE,'steam','team',2016,NULL,'200만+',18860,'[{"name":"Unreal Engine 2.5","role":"엔진","confirmed":true}]'::jsonb),
 ('dead-frontier-2','Dead Frontier 2','Creaky Corpse Ltd','Unity',TRUE,'steam','team',2019,NULL,'200만+',18844,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('a-plague-tale-requiem','A Plague Tale: Requiem','Asobo Studio','Zouna',TRUE,'steam','team',2022,NULL,'50만+',18772,'[{"name":"Zouna","role":"엔진","confirmed":true}]'::jsonb),
 ('children-of-morta','Children of Morta','Dead Mage','Unity',TRUE,'steam','team',2019,NULL,'100만+',18625,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('bopl-battle','Bopl Battle','Johan Grönvall','Unity',TRUE,'steam','team',2023,NULL,'100만+',18609,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('call-to-arms','Call to Arms','Digitalmindsoft','GEM 2',TRUE,'steam','team',2018,NULL,'100만+',18474,'[{"name":"GEM 2","role":"엔진","confirmed":true}]'::jsonb),
 ('day-of-infamy','Day of Infamy','New World Interactive','Source',TRUE,'steam','team',2017,NULL,'100만+',18172,'[{"name":"Source","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-infinite-warfare','Call of Duty: Infinite Warfare','Infinity Ward','IW engine',TRUE,'steam','team',2016,NULL,'100만+',16982,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('dc-universe-online','DC Universe Online','Dimensional Ink Games','Unreal Engine 3',TRUE,'steam','team',2011,NULL,'100만+',16923,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('crash-bandicoot-n-sane-trilogy','Crash Bandicoot N. Sane Trilogy','Vicarious Visions','Vicarious Visions Alchemy',TRUE,'steam','team',2018,NULL,'100만+',16702,'[{"name":"Vicarious Visions Alchemy","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-modern-warfare','Call of Duty: Modern Warfare','Infinity Ward','IW engine',TRUE,'steam','team',2019,NULL,'100만+',16610,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('darkest-dungeon-ii','Darkest Dungeon II','Red Hook Studios','Unity',TRUE,'steam','team',2023,NULL,'100만+',16355,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('atlyss','ATLYSS','Kiseff','Unity',TRUE,'indie','team',2024,NULL,'20만+',16289,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('antichamber','Antichamber','Alexander Bruce','Unreal Engine 3',TRUE,'steam','team',2013,NULL,'100만+',16269,'[{"name":"Unreal Engine 3","role":"엔진","confirmed":true}]'::jsonb),
 ('bless-unleashed','Bless Unleashed','VALOFE','Unreal Engine 4',TRUE,'steam','team',2021,NULL,'200만+',16259,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('clustertruck','Clustertruck','Landfall','Unity',TRUE,'steam','team',2016,NULL,'100만+',16041,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('company-of-heroes','Company of Heroes','Relic Entertainment','Essence Engine',TRUE,'steam','team',2006,NULL,'100만+',16025,'[{"name":"Essence Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('60-seconds-reatomized','60 Seconds! Reatomized','Robot Gentleman','Unity',TRUE,'steam','team',2019,NULL,'100만+',15967,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-black-ops-cold-war','Call of Duty: Black Ops Cold War','Treyarch','IW engine',TRUE,'steam','team',2020,NULL,'50만+',15797,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('cooking-simulator','Cooking Simulator','Big Cheese Studio','Unity',TRUE,'steam','team',2019,NULL,'50만+',15767,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('crosscode','CrossCode','Radical Fish Games','NW.js',TRUE,'steam','team',2018,NULL,'50만+',15699,'[{"name":"NW.js","role":"엔진","confirmed":true}]'::jsonb),
 ('action-taimanin','Action Taimanin','LiLith','Unity',TRUE,'steam','team',2020,NULL,'100만+',15495,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('call-of-duty-black-ops','Call of Duty: Black Ops','Treyarch','IW engine',TRUE,'steam','team',2010,NULL,'200만+',15124,'[{"name":"IW engine","role":"엔진","confirmed":true}]'::jsonb),
 ('baldur-s-gate-enhanced-edition','Baldur''s Gate: Enhanced Edition','Beamdog','Infinity',TRUE,'steam','team',2012,NULL,'100만+',15123,'[{"name":"Infinity","role":"엔진","confirmed":true}]'::jsonb),
 ('age-of-mythology-retold','Age of Mythology: Retold','World''s Edge','BANG!',TRUE,'steam','team',2024,NULL,'50만+',15043,'[{"name":"BANG!","role":"엔진","confirmed":true}]'::jsonb),
 ('darwin-project','Darwin Project','Scavengers Studio','Unreal Engine 4',TRUE,'steam','team',2020,NULL,'100만+',14978,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('changed','Changed','DragonSnow','RPG Maker',TRUE,'steam','team',2018,NULL,'50만+',14935,'[{"name":"RPG Maker","role":"엔진","confirmed":true}]'::jsonb),
 ('age-of-wonders-4','Age of Wonders 4','Triumph Studios','Creator',TRUE,'steam','team',2023,NULL,'50만+',14901,'[{"name":"Creator","role":"엔진","confirmed":true}]'::jsonb),
 ('dawn-of-man','Dawn of Man','Madruga Works','Unity',TRUE,'steam','team',2019,NULL,'100만+',14845,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('911-operator','911 Operator','Jutsu Games','Unity',TRUE,'steam','team',2017,NULL,'50만+',14616,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('creative-destruction','Creative Destruction','NetEase Games','NeoX',TRUE,'steam','team',2018,NULL,'200만+',14571,'[{"name":"NeoX","role":"엔진","confirmed":true}]'::jsonb),
 ('choo-choo-charles','Choo-Choo Charles','Two Star Games','Unreal Engine 4',TRUE,'steam','team',2022,NULL,'50만+',14293,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('darksiders-warmastered-edition','Darksiders Warmastered Edition','KAIKO','Phoenix Engine',TRUE,'steam','team',2016,NULL,'100만+',13991,'[{"name":"Phoenix Engine","role":"엔진","confirmed":true}]'::jsonb),
 ('aliens-dark-descent','Aliens: Dark Descent','Tindalos Interactive','Unreal Engine 4',TRUE,'steam','team',2023,NULL,'50만+',13803,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('car-mechanic-simulator-2015','Car Mechanic Simulator 2015','Red Dot Games','Unity',TRUE,'steam','team',2015,NULL,'50만+',13466,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('counter-strike-condition-zero','Counter-Strike: Condition Zero','Valve','GoldSrc',TRUE,'steam','aaa',2004,NULL,'1000만+',13442,'[{"name":"GoldSrc","role":"엔진","confirmed":true}]'::jsonb),
 ('backpack-battles','Backpack Battles','PlayWithFurcifer','Godot',TRUE,'steam','team',2025,NULL,'50만+',13410,'[{"name":"Godot","role":"엔진","confirmed":true}]'::jsonb),
 ('cat-goes-fishing','Cat Goes Fishing','Cat5Games','GameMaker',TRUE,'steam','team',2015,NULL,'50만+',13316,'[{"name":"GameMaker","role":"엔진","confirmed":true}]'::jsonb),
 ('century-age-of-ashes','Century: Age of Ashes','Playwing LTD','Unreal Engine 4',TRUE,'steam','team',2021,NULL,'200만+',13226,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb),
 ('blasphemous-2-2','Blasphemous 2','The Game Kitchen','Unity',TRUE,'steam','team',2023,NULL,'50만+',13000,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('bomber-crew','Bomber Crew','Runner Duck','Unity',TRUE,'steam','team',2017,NULL,'50만+',12925,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('armello','Armello','League of Geeks','Unity',TRUE,'steam','team',2015,NULL,'100만+',12911,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('bioshock-2','BioShock 2','2K Marin','Unreal Engine 2.5',TRUE,'steam','team',2010,NULL,'100만+',12864,'[{"name":"Unreal Engine 2.5","role":"엔진","confirmed":true}]'::jsonb),
 ('cloudpunk','Cloudpunk','ION LANDS','Unity',TRUE,'steam','team',2020,NULL,'50만+',12760,'[{"name":"Unity","role":"엔진","confirmed":true}]'::jsonb),
 ('a-game-about-digging-a-hole','A Game About Digging A Hole','DoubleBee','Unreal Engine 5',TRUE,'steam','team',2025,NULL,'50만+',12737,'[{"name":"Unreal Engine 5","role":"엔진","confirmed":true}]'::jsonb),
 ('breathedge','Breathedge','RedRuins Softworks','Unreal Engine 4',TRUE,'steam','team',2021,NULL,'100만+',12620,'[{"name":"Unreal Engine 4","role":"엔진","confirmed":true}]'::jsonb)
ON CONFLICT (slug) DO NOTHING;
